# This is a basic workflow to help you get started with Actions

name: build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  x64:
    # The type of runner that the job will run on
    runs-on: windows-2019
    
    defaults:
      run:
        shell: msys2 {0}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      # Runs a single command using the runners shell
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            base-devel
            git
            p7zip
            mingw64/mingw-w64-x86_64-gcc
            mingw64/mingw-w64-x86_64-diffutils
            mingw64/mingw-w64-x86_64-nasm
            mingw64/mingw-w64-x86_64-pkg-config
      
      - name: Install packages
        run: ./install_x64.sh
      
      - name: Configure
        run: ./configure.sh
      
      - name: Build
        run: |
          cd ffmpeg
          make && make install
      
      - name: Package files
        run: 7z -mx9 -y a ffmpeg.7z bin/*

      - name: Upload file
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg-x64
          path: ffmpeg.7z
